name: Trigger auto deployment for ter-ca-java

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/ter-ca-java-AutoDeployTrigger-93969c88-d675-48e0-a1ac-b271dda4f1b9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TERCAJAVA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TERCAJAVA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TERCAJAVA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src 
          registryUrl: docker.io
          registryUsername: ${{ secrets.TERCAJAVA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TERCAJAVA_REGISTRY_PASSWORD }}
          containerAppName: ter-ca-java
          resourceGroup: ter-RG
          imageToBuild: amrish24/ter-ca-java:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


